# Generated by Django 5.2.1 on 2025-06-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_role_alter_profile_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favorites',
            new_name='favourites',
        ),
    ]
