# Generated by Django 5.2 on 2025-06-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_phone_number"),
        ("products", "0007_alter_product_sale_price"),
        ("shop", "0002_cart_size_alter_cart_product_alter_cart_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user", "product", "size")},
        ),
    ]
