# Generated by Django 5.2.1 on 2025-06-22 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_sale_price'),
        ('shop', '0004_status_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.ForeignKey(default='M', on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
    ]
