# Generated by Django 5.2 on 2025-06-27 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_sale_price"),
        ("shop", "0008_returnrequest"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderproduct",
            unique_together={("order", "product", "size")},
        ),
    ]
