# Generated by Django 5.2 on 2025-06-28 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_orderproduct_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="returnrequest",
            name="product",
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="order_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.orderproduct",
            ),
        ),
    ]
