# Generated by Django 5.2 on 2025-06-28 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_returnrequest_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnrequest",
            name="order_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.orderproduct"
            ),
        ),
    ]
