# Generated by Django 5.2.1 on 2025-07-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_user_email_orderproduct_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
        migrations.AlterModelTable(
            name='orderproduct',
            table='OrderProducts',
        ),
        migrations.AlterModelTable(
            name='status',
            table='Statuses',
        ),
    ]
