# Generated by Django 5.2 on 2025-06-11 16:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_is_sale_product_sale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
