# Generated by Django 5.2.1 on 2025-07-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
        migrations.AlterModelTable(
            name='productstock',
            table='Product_stock',
        ),
    ]
